import type { Metadata } from 'next';
import './globals.css';
import { manrope } from '@/utils/fonts';
import DashboardWrapper from '@/dashboard/dashboardWrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={manrope.variable}>
      <body className='min-h-full flex flex-col'>
        <time dateTime='2026-03-25' suppressHydrationWarning />
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
